### ISSUE TITLE
members section - exec team, project members, advisors/alumni

### ISSUE THREAD

**Issue by cindyjyuan** [codebase-berkeley/codebase-website#44]
website links, i'll upload member photos here

**Comment by c0dyzeng** [comment]
hi could you upload member photos here?

**Comment by cindyjyuan** [comment]
done 
https://drive.google.com/drive/u/0/folders/1wsT338KvVyMVcS_t4lorAv_EG2Cy8hDT

**Comment by OldGuo** [comment]
@cindyjyuan @c0dyzeng one note about pictures. Currently all our images are super high-res ~3000x3000 pixels and loading them all when you're on `/about` is super heavy on the networking request and also tough on the browser. Since these images are small anyway, I think we should upload reduced quality versions!

**Comment by c0dyzeng** [comment]
ohhhh so no wonder shit didn't load on chrome and I had to use firefox

**Comment by c0dyzeng** [comment]
heheheheh

**Comment by OldGuo** [comment]
LOOOOOOOOOL

**Comment by OldGuo** [comment]
@c0dyzeng closing this?

**Comment by OldGuo** [comment]
Actually I think these cards aren't centered
![image](https://user-images.githubusercontent.com/2722397/44319209-51d19100-a3ef-11e8-973d-4fe7b73b80d4.png)

**Comment by cindyjyuan** [comment]
centered it
